### ISSUE TITLE
Missing maven deps

### ISSUE THREAD

**Issue by mhicauber** [entur/marduk#5]
When building with maven, some deps missing, especially one bus away libs and osrmpbf.
Are there some additonal repos to specify ?

**Comment by vpaturet** [comment]
Currently Marduk uses the following dependencies that are not available in a public Maven repository:
- org.rutebanken.superpom:superpom (sources available here: https://github.com/entur/superpom)
- org.entur.helpers:* (sources available here: : https://github.com/entur/rutebanken-helpers)
- com.google.cloud:pubsub-emulator (used only for testing, can be skipped by setting the property entur.google.pubsub.emulator.download.skip=true)
